services:
  # Web application service
  web:
    build:
      context: .
      dockerfile: Dockerfile.temp
    container_name: marketsage-web-dev
    restart: always
    platform: linux/amd64
    ports:
      - "3030:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://marketsage:marketsage_password@db:5432/marketsage?schema=public
      - NODE_ENV=development
      - NEXTAUTH_URL=http://localhost:3030
      - NEXTAUTH_SECRET=this-is-a-development-secret-key-replace-in-production
    networks:
      - marketsage-network
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next

  # PostgreSQL database service
  db:
    image: postgres:16-alpine
    container_name: marketsage-db
    restart: always
    platform: linux/amd64
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=marketsage
      - POSTGRES_PASSWORD=marketsage_password
      - POSTGRES_DB=marketsage
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - marketsage-network

volumes:
  postgres-data:
    driver: local

networks:
  marketsage-network:
    driver: bridge 